# Generated by Django 2.2.2 on 2019-07-03 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False, verbose_name='Статус работы MongoDB')),
                ('process_id', models.IntegerField(default=-1, verbose_name='PID процесса, в котором работает MongoDB')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления статуса MongoDB')),
            ],
        ),
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('mongo_collection', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_message_text', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
